# Generated by Django 4.1.3 on 2022-12-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_answer_alter_question_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('category',)},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
